version: "3.8"

services:
  # Database
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress-wd
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - wpsite
  # Phpmyadmin
  phpmyadmin:
    depends_on: 
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment: 
      PMA_HOST: db:3306
      MYSQL_ROOT_PASSWORD: password
    networks: 
      - wpsite
  # WordPress
  wordpress:
    depends_on:
      - db
      - phpmyadmin
    image: wordpress:5.6.0
    ports:
      - '8001:80'
    restart: always
    volumes: ['./src:/var/www/html']
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
    networks: 
      - wpsite
networks:
  wpsite:
volumes:
  db_data: